apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "productionstack-status-reporter.fullname" . }}
  namespace: {{ include "productionstack-status-reporter.namespace" . }}
  labels:
    {{- include "productionstack-status-reporter.labels" . | nindent 4 }}
