apiVersion: v1
kind: Service
metadata:
  name: {{ include "modeldeployment.eppServiceName" . }}
  namespace: {{ include "modeldeployment.namespace" . }}
  labels:
    {{- include "modeldeployment.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "modeldeployment.eppSelectorLabels" . | nindent 4 }}
  ports:
    - name: grpc-ext-proc
      protocol: TCP
      port: {{ .Values.epp.extProcPort }}
      targetPort: {{ .Values.epp.extProcPort }}
      appProtocol: grpc
    - name: http-metrics
      protocol: TCP
      port: {{ .Values.epp.metricsPort }}
      targetPort: {{ .Values.epp.metricsPort }}
