apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gpu-node-mocker.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gpu-node-mocker.labels" . | nindent 4 }}
