apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gpu-node-mocker.fullname" . }}
  namespace: {{ include "gpu-node-mocker.namespace" . }}
  labels:
    {{- include "gpu-node-mocker.labels" . | nindent 4 }}
